[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "PyHiveLMS"
version = "2.1.3"
description = "Python bindings for Hive"
authors = [
    { name = "Michael K. Steinberg", email = "m.kuper.steinberg@gmail.com" },
]
requires-python = ">=3.11.0"
dependencies = [
    "httpx>=0.28.1",
    "python-dateutil>=2.9.0",
    "attrs>=25.4.0",
    "typer>=0.20.0",
    "flask>=3.1.3",
    "pydantic>=2.12.5",
    "keyring",
]
readme = "README.md"

[project.optional-dependencies]
dev = ["pytest>=9.0.2", "pytest-httpx>=0.36.0", "types-python-dateutil>=0.1.0"]
codegen = ["datamodel-code-generator[http]>=0.66", "pyyaml>=6.0"]

[project.scripts]
pyhive = "pyhive.cli.cli:main"

[dependency-groups]
dev = ["pre-commit>=4.2.0", "pytest-cov>=6.2.1", "pytest>=7.4.0"]

[tool.hatch.build.targets.wheel]
packages = ["pyhive"]

[tool.hatch.build.hooks.custom]
path = "scripts/generate_versions.py"

[tool.api_versions]
supported = ["5.1.2", "6.2.0", "6.4.0", "7.1.0"]

[tool.ruff.lint]
ignore = [
    "BLE001", # broad-exception-caught
    "RET504", # unnecessary-assign
    "ARG001", # unused-argument
]

[tool.mypy]
plugins = []
mypy_path = "$MYPY_CONFIG_FILE_DIR,$MYPY_CONFIG_FILE_DIR/stubs"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
check_untyped_defs = true
disallow_any_generics = true
disallow_subclassing_any = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true
show_error_codes = true
no_implicit_optional = true
ignore_missing_imports = false
disallow_any_unimported = true
exclude = "([a-zA-Z]*/(tests)/(.)*)|.venv"
