"""Emit ``_generated/enums.py`` in PyHive's enum style."""

from __future__ import annotations

import re

from .spec import EnumSchema, Spec

_NON_IDENT = re.compile(r"[^0-9a-zA-Z]+")


def member_name(value: object, label: str | None, is_int: bool) -> str:
    """Derive a PyHive enum member identifier.

    String enums name members after the *value* (``"On Done"`` -> ``ON_DONE``);
    integer enums name members after the spec *label* (``1``/``Hanich`` ->
    ``HANICH``). camelCase is upper-cased, not split (``AutoChecked`` ->
    ``AUTOCHECKED``).
    """

    basis = label if (is_int and label) else str(value)
    name = _NON_IDENT.sub("_", basis).strip("_").upper()
    if not name:
        name = f"VALUE_{value}"
    if name[0].isdigit():
        name = f"_{name}"
    return name


def _render_enum(enum: EnumSchema) -> str:
    base = "IntEnum" if enum.is_int else "str, Enum"
    lines = [f"class {enum.name}({base}):", f'    """{enum.name}."""', ""]
    seen: set[str] = set()
    for value, label in enum.members:
        ident = member_name(value, label, enum.is_int)
        # Guard against accidental duplicate identifiers.
        if ident in seen:
            ident = f"{ident}_{value}"
        seen.add(ident)
        rendered = repr(value) if not enum.is_int else str(value)
        lines.append(f"    {ident} = {rendered}")
    lines += [
        "",
        "    def __str__(self) -> str:",
        "        return str(self.value)",
    ]
    return "\n".join(lines)


def render_enums_module(spec: Spec) -> str:
    """Render the full ``enums.py`` source."""

    has_int = any(e.is_int for e in spec.enums.values())
    has_str = any(not e.is_int for e in spec.enums.values())
    imports = []
    if has_int and has_str:
        imports.append("from enum import Enum, IntEnum")
    elif has_int:
        imports.append("from enum import IntEnum")
    else:
        imports.append("from enum import Enum")

    blocks = [_render_enum(spec.enums[name]) for name in sorted(spec.enums)]
    header = (
        '"""Hive API enums — AUTO-GENERATED by tools/hive_codegen. Do not edit.\n\n'
        f"Generated from Hive OpenAPI spec version {spec.version}.\n"
        '"""\n\n'
        + "\n".join(imports)
        + "\n\n\n"
    )
    body = "\n\n\n".join(blocks)
    exports = ",\n".join(f'    "{name}"' for name in sorted(spec.enums))
    footer = f"\n\n\n__all__ = [\n{exports},\n]\n"
    return header + body + footer
