"""Hive API enums — AUTO-GENERATED by tools/hive_codegen. Do not edit.

Generated from Hive OpenAPI spec version 7.3.0.
"""

from enum import Enum, IntEnum


class ActionEnum(str, Enum):
    """ActionEnum."""

    HANDLING = "Handling"
    NO_CHECK = "No Check"
    BUILT = "Built"
    FINISHED = "Finished"
    SENDING = "Sending"
    ERROR = "Error"
    SUCCESS = "Success"

    def __str__(self) -> str:
        return str(self.value)


class AssignmentResponseTypeEnum(str, Enum):
    """AssignmentResponseTypeEnum."""

    COMMENT = "Comment"
    WORK_IN_PROGRESS = "Work In Progress"
    SUBMISSION = "Submission"
    AUTOCHECK = "AutoCheck"
    REDO = "Redo"
    DONE = "Done"

    def __str__(self) -> str:
        return str(self.value)


class AssignmentStatusEnum(str, Enum):
    """AssignmentStatusEnum."""

    NEW = "New"
    WORK_IN_PROGRESS = "Work In Progress"
    REDO = "Redo"
    SUBMITTED = "Submitted"
    AUTOCHECKED = "AutoChecked"
    DONE = "Done"

    def __str__(self) -> str:
        return str(self.value)


class ClassTypeEnum(str, Enum):
    """ClassTypeEnum."""

    ROOM = "Room"
    STUDENT_GROUP = "Student Group"

    def __str__(self) -> str:
        return str(self.value)


class ClearanceEnum(IntEnum):
    """ClearanceEnum."""

    HANICH = 1
    CHECKER = 2
    SEGEL = 3
    ADMIN = 5

    def __str__(self) -> str:
        return str(self.value)


class ExercisePreviewTypes(str, Enum):
    """ExercisePreviewTypes."""

    DISABLED = "Disabled"
    MARKDOWN = "Markdown"
    PDF = "PDF"

    def __str__(self) -> str:
        return str(self.value)


class FormFieldTypeEnum(str, Enum):
    """FormFieldTypeEnum."""

    TEXT = "text"
    NUMBER = "number"
    MULTIPLE = "multiple"
    MULTIRESPONSE = "multiResponse"

    def __str__(self) -> str:
        return str(self.value)


class GenderEnum(str, Enum):
    """GenderEnum."""

    MALE = "Male"
    FEMALE = "Female"
    NONBINARY = "NonBinary"

    def __str__(self) -> str:
        return str(self.value)


class HelpResponseTypeEnum(str, Enum):
    """HelpResponseTypeEnum."""

    RESOLVE = "Resolve"
    OPEN = "Open"
    COMMENT = "Comment"

    def __str__(self) -> str:
        return str(self.value)


class HelpStatusEnum(str, Enum):
    """HelpStatusEnum."""

    RESOLVED = "Resolved"
    OPEN = "Open"

    def __str__(self) -> str:
        return str(self.value)


class HelpTypeEnum(str, Enum):
    """HelpTypeEnum."""

    EXERCISE = "Exercise"
    MEDICAL = "Medical"
    ERROR = "Error"
    MUSIC = "Music"
    REQUEST = "Request"
    OTHER = "Other"
    CHAT = "Chat"

    def __str__(self) -> str:
        return str(self.value)


class MeClearanceEnum(IntEnum):
    """MeClearanceEnum."""

    _1 = 1
    _2 = 2
    _3 = 3
    _5 = 5

    def __str__(self) -> str:
        return str(self.value)


class NotificationResponseTypeEnum(str, Enum):
    """NotificationResponseTypeEnum."""

    COMMENT = "Comment"
    WORK_IN_PROGRESS = "Work In Progress"
    SUBMISSION = "Submission"
    AUTOCHECK = "AutoCheck"
    REDO = "Redo"
    DONE = "Done"
    RESOLVE = "Resolve"
    OPEN = "Open"

    def __str__(self) -> str:
        return str(self.value)


class PatbasEnum(str, Enum):
    """PatbasEnum."""

    NEVER = "Never"
    ON_DONE = "On Done"
    ALWAYS = "Always"
    STAFF_ONLY = "Staff Only"

    def __str__(self) -> str:
        return str(self.value)


class QueueRuleEnum(str, Enum):
    """QueueRuleEnum."""

    CHOOSE = "Choose"
    WAIT_FOR_SUBMITTED = "Wait For Submitted"
    WAIT_FOR_AUTOCHECKS = "Wait For AutoChecks"
    WAIT_FOR_DONE = "Wait For Done"

    def __str__(self) -> str:
        return str(self.value)


class StatusEnum(str, Enum):
    """StatusEnum."""

    PRESENT = "Present"
    RAISED_HAND = "Raised Hand"
    TOILET_REQUEST = "Toilet Request"
    TOILET = "Toilet"
    PERSONAL_TALK = "Personal Talk"
    WORK_TALK = "Work Talk"
    MEDICAL = "Medical"
    PRAYER = "Prayer"
    ROOM = "Room"
    HOME = "Home"

    def __str__(self) -> str:
        return str(self.value)


class SyncStatusEnum(str, Enum):
    """SyncStatusEnum."""

    CREATING = "Creating"
    DELETING = "Deleting"
    NORMAL = "Normal"
    ERROR = "Error"

    def __str__(self) -> str:
        return str(self.value)


class VisibilityEnum(str, Enum):
    """VisibilityEnum."""

    ALL_STAFF = "All Staff"
    ALL_STAFF_AND_CHECKERS = "All Staff And Checkers"
    AUTHOR_ONLY = "Author Only"

    def __str__(self) -> str:
        return str(self.value)


__all__ = [
    "ActionEnum",
    "AssignmentResponseTypeEnum",
    "AssignmentStatusEnum",
    "ClassTypeEnum",
    "ClearanceEnum",
    "ExercisePreviewTypes",
    "FormFieldTypeEnum",
    "GenderEnum",
    "HelpResponseTypeEnum",
    "HelpStatusEnum",
    "HelpTypeEnum",
    "MeClearanceEnum",
    "NotificationResponseTypeEnum",
    "PatbasEnum",
    "QueueRuleEnum",
    "StatusEnum",
    "SyncStatusEnum",
    "VisibilityEnum",
]
