"""Hive API model bases — AUTO-GENERATED by tools/hive_codegen. Do not edit.

Generated from Hive OpenAPI spec version 7.3.0.
The curated layer (pyhive/src/types/*.py) subclasses these bases.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any
from pydantic import Field
from pyhive.src.types.core_item import HiveCoreItem
from uuid import UUID
from .enums import (
    ActionEnum,
    AssignmentResponseTypeEnum,
    AssignmentStatusEnum,
    ClassTypeEnum,
    ClearanceEnum,
    ExercisePreviewTypes,
    FormFieldTypeEnum,
    GenderEnum,
    HelpResponseTypeEnum,
    HelpStatusEnum,
    HelpTypeEnum,
    MeClearanceEnum,
    NotificationResponseTypeEnum,
    PatbasEnum,
    QueueRuleEnum,
    StatusEnum,
    SyncStatusEnum,
    VisibilityEnum,
)


class AssignmentNotification(HiveCoreItem):
    id: int
    user_id: Annotated[int, Field(alias="user")]
    user_name: str
    exercise_id: Annotated[int, Field(alias="exercise")]
    module_id: Annotated[int, Field(alias="module")]
    subject: int
    last_staff_updated: datetime


class AssignmentResponseContent(HiveCoreItem):
    raw_content: Annotated[str, Field(alias="content")]
    field_id: Annotated[int, Field(alias="field")]


class ClientInfoResponse(HiveCoreItem):
    name: str
    """
    The registered name of the application.
    """
    scopes: dict[str, str]
    """
    Key-value mapping of all available OAuth scopes.
    """


class CourseTokenObtainPair(HiveCoreItem):
    access: str
    refresh: str


class Attendee(HiveCoreItem):
    description: Annotated[str | None, Field(...)]
    name: str
    id: int


class Event(HiveCoreItem):
    id: UUID | None = None
    title: str | None = None
    start: datetime
    end: datetime
    category_id: UUID | None = None
    room_id: int | None = None
    lesson_id: UUID | None = None
    attendees: list[Attendee]
    hidden_from_students: bool | None = None
    locked: bool | None = None
    description: str | None = ""
    color: str
    category_name: str


class EventAttendee(HiveCoreItem):
    id: UUID | None = None
    event_id: UUID
    attendee_class_id: int


class EventCategory(HiveCoreItem):
    id: UUID | None = None
    name: str
    color: str
    students_see_subject: bool | None = None
    visible_to_students: bool | None = None
    has_lesson: bool | None = None
    hide_details_in_review: bool | None = None


class EventInstructor(HiveCoreItem):
    id: UUID | None = None
    event_id: UUID
    instructor_id: int


class EventTag(HiveCoreItem):
    id: UUID | None = None
    name: str
    color: str


class EventTagging(HiveCoreItem):
    id: UUID | None = None
    event_id: UUID
    tag_id: UUID


class HelpNotification(HiveCoreItem):
    id: int
    user_name: str
    last_staff_updated: datetime


class Lesson(HiveCoreItem):
    id: UUID | None = None
    name: str
    module_id: int
    module_order: str
    module_name: str
    subject_symbol: str
    subject_name: str
    program_name: str
    description: str | None = None


class NotificationNested(HiveCoreItem):
    id: int
    from_user_id: Annotated[int | None, Field(alias="from_user")] = None
    comment: str | None = None


class PowerSyncToken(HiveCoreItem):
    token: str
    endpoint: str
    expiresAt: int


class Queue(HiveCoreItem):
    id: int
    name: str
    description: str | None = None
    module_id: Annotated[int | None, Field(alias="module")] = None
    user_id: Annotated[int | None, Field(alias="user")] = None
    user_id_1: Annotated[int | None, Field(alias="user_id")]
    user_name: Annotated[str | None, Field(...)]
    subject_id: Annotated[int | None, Field(...)]
    subject_name: Annotated[str | None, Field(...)]
    subject_color: Annotated[str | None, Field(...)]
    subject_symbol: Annotated[str | None, Field(...)]
    module_id_1: Annotated[int | None, Field(alias="module_id")]
    module_name: Annotated[str | None, Field(...)]
    module_order: Annotated[str | None, Field(...)]
    program_id: int
    program_name: str


class RegisterCourseUser(HiveCoreItem):
    first_name: str
    last_name: str
    username: str
    """
    Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    """
    gender: GenderEnum
    password: str


class SSOApplication(HiveCoreItem):
    id: int
    name: str | None = None
    redirect_uris: str | None = None
    """
    Allowed URIs list, space separated
    """
    client_id: str
    client_secret: str
    """
    Client secret for authentication
    """
    owner: Annotated[str | None, Field(...)]
    skip_authorization: bool


class SSOTokenExchangeResponse(HiveCoreItem):
    access_token: str
    """
    Native Hive JWT access token.
    """
    refresh_token: str
    """
    Native Hive JWT refresh token.
    """
    expires_at: int
    """
    Expiry of the access token, as a UNIX timestamp.
    """


class Seating(HiveCoreItem):
    id: int
    hostname: str | None = None
    hanich: int | None = None
    classroom: int
    x: int
    y: int


class Status(HiveCoreItem):
    id: int
    time: datetime
    action: ActionEnum
    payload: str | None = None


class Tag(HiveCoreItem):
    id: int
    name: str
    color: str


class TokenRefresh(HiveCoreItem):
    access: str
    refresh: str


class TopHelpResponseChecker(HiveCoreItem):
    contents: str | None = None


class Assignment(HiveCoreItem):
    id: int
    user_id: Annotated[int, Field(alias="user")]
    checker_id: Annotated[int | None, Field(alias="checker")]
    checker_first_name: str | None = None
    checker_last_name: str | None = None
    is_subscribed: bool
    exercise_id: Annotated[int, Field(alias="exercise")]
    assignment_status: AssignmentStatusEnum
    student_assignment_status: AssignmentStatusEnum | None = None
    patbas: bool
    description: str | None = None
    submission_count: int | None = None
    total_check_count: int | None = None
    manual_check_count: int | None = None
    last_staff_updated: datetime
    flagged: bool | None = None
    work_time: int
    timer: str | None = None


class AssignmentOptionHanich(HiveCoreItem):
    id: int
    exercise_id: Annotated[int, Field(alias="exercise")]
    exercise_name: str
    parent_module_id: Annotated[int, Field(alias="parent_module")]
    parent_subject_id: Annotated[int, Field(alias="parent_subject")]
    parent_module_name: str
    parent_subject_symbol: str
    parent_subject_color: str
    assignment_status: AssignmentStatusEnum


class AssignmentResponse(HiveCoreItem):
    id: int
    user_id: Annotated[int, Field(alias="user")]
    file_name: str | None = None
    dear_student: bool | None = True
    date: datetime
    hide_checker_name: bool | None = None
    segel_only: bool | None = None
    response_type: AssignmentResponseTypeEnum


class Class(HiveCoreItem):
    id: int
    name: str
    display_name: str
    program_id: Annotated[int, Field(alias="program")]
    user_ids: Annotated[list[int], Field(alias="users")]
    email: str | None = None
    type_: Annotated[ClassTypeEnum | None, Field(alias="type")] = None
    program_name: Annotated[str, Field(alias="program__name")]
    description: str | None = None


class CourseUser(HiveCoreItem):
    id: int
    display_name: str
    clearance: ClearanceEnum
    avatar_filename: str | None = None
    gender: GenderEnum
    number: int | None = None
    program_id: Annotated[int | None, Field(alias="program")] = None
    checkers_brief: str | None = None
    current_assignment_id: Annotated[int | None, Field(alias="current_assignment")] = (
        None
    )
    current_assignment_options: list[int]
    mentor_id: Annotated[int | None, Field(alias="mentor")] = None
    class_ids: Annotated[list[int] | None, Field(alias="classes")] = None
    mentee_ids: Annotated[list[int], Field(alias="mentees")]
    username: str
    """
    Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    """
    first_name: str | None = None
    last_name: str | None = None
    status: StatusEnum
    status_date: datetime
    queue_id: Annotated[int | None, Field(alias="queue")] = None
    disable_queue: bool | None = None
    user_queue_id: Annotated[int | None, Field(alias="user_queue")] = None
    disable_user_queue: bool | None = None
    override_queue_id: Annotated[int | None, Field(alias="override_queue")] = None
    confirmed: bool | None = None
    teacher: bool | None = None
    hostname: str | None = None


class Exercise(HiveCoreItem):
    id: int
    name: str
    parent_module_id: Annotated[int, Field(alias="parent_module")]
    parent_subject_id: Annotated[int, Field(alias="parent_subject")]
    parent_module_name: str
    parent_subject_symbol: str
    parent_subject_color: str
    download: bool
    preview: ExercisePreviewTypes
    patbas_preview: ExercisePreviewTypes | None = None
    patbas_download: bool | None = None
    is_lecture: bool | None = None
    style: str | None = None
    parent_subject_name: str
    parent_module_order: str
    order: str
    tags: list[str]
    patbas: PatbasEnum
    on_creation_data: Any | None = None
    autocheck_tag: str | None = None
    autodone: bool | None = None
    expected_duration: str | None = None
    sync_status: SyncStatusEnum
    sync_message: str | None = None
    segel_path: str
    """
    The path that is accessible to staff from their computers
    """
    segel_brief: str | None = None


class FormField(HiveCoreItem):
    id: int
    name: str
    description: str | None = None
    type_: Annotated[FormFieldTypeEnum, Field(alias="type")]
    order: int
    required: bool
    staff_responses: bool
    hanich_responses: bool
    has_value: bool
    lower_limit: int | None = None
    upper_limit: int | None = None
    choices: list[str] | None = None
    segel_only: bool
    metadata: Any | None = None
    group_ids: Annotated[list[int] | None, Field(alias="groups")] = None


class FormFieldTopResponse(HiveCoreItem):
    id: int
    exercise_id: Annotated[int, Field(alias="exercise")]
    name: str
    description: str | None = None
    type_: Annotated[FormFieldTypeEnum, Field(alias="type")]
    order: int
    required: bool
    staff_responses: bool
    hanich_responses: bool
    has_value: bool
    lower_limit: int | None = None
    upper_limit: int | None = None
    choices: list[str] | None = None
    segel_only: bool
    metadata: Any | None = None
    group_ids: Annotated[list[int] | None, Field(alias="groups")] = None
    top_responses: list[str]


class Help(HiveCoreItem):
    id: int
    user_id: Annotated[int, Field(alias="user")]
    checker_id: Annotated[int | None, Field(alias="checker")] = None
    checker_first_name: str | None = None
    checker_last_name: str | None = None
    is_subscribed: bool
    title: str | None = None
    help_type: HelpTypeEnum
    help_status: HelpStatusEnum
    visibility: VisibilityEnum | None = None


class HelpResponse(HiveCoreItem):
    id: int
    user_id: Annotated[int, Field(alias="user")]
    contents: str | None = None
    file_name: str | None = None
    dear_student: bool = True
    date: datetime
    hide_checker_name: bool | None = None
    segel_only: bool | None = None
    response_type: HelpResponseTypeEnum


class HelpResponseSegelNested(HiveCoreItem):
    id: int
    user_id: Annotated[int, Field(alias="user")]
    contents: str | None = None
    file_name: str | None = None
    dear_student: bool = True
    date: datetime
    hide_checker_name: bool | None = None
    segel_only: bool | None = None
    response_type: HelpResponseTypeEnum


class LessonRule(HiveCoreItem):
    id: UUID
    parent_rule: UUID | None = None
    student_groups: list[int] | None = None
    queue_id: Annotated[int | None, Field(alias="queue")] = None
    queue_data: Annotated[Queue | None, Field(...)]
    student_groups_data: Annotated[list[Class] | None, Field(...)]


class Me(HiveCoreItem):
    id: int
    only_today: bool
    display_name: str
    number: Annotated[int | None, Field(...)]
    program_id: Annotated[int | None, Field(alias="program")]
    clearance: MeClearanceEnum
    status: StatusEnum
    current_assignment_id: Annotated[int | None, Field(alias="current_assignment")] = (
        None
    )
    current_assignment_options: list[AssignmentOptionHanich]
    confirmed: bool | None = None
    current_assignment__exercise_name: str
    current_assignment__exercise_id: int
    current_assignment__module_id: int
    current_assignment__subject_id: int
    username: str
    """
    Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    """
    program_name: Annotated[str, Field(alias="program__name")]
    schedule_enabled: bool
    hanich_raise_hand: bool
    teacher: bool


class Module(HiveCoreItem):
    id: int
    name: str
    parent_subject_id: Annotated[int, Field(alias="parent_subject")]
    order: str
    sync_status: SyncStatusEnum
    sync_message: str | None = None
    parent_program_name: str
    parent_subject_name: str
    parent_subject_symbol: str
    segel_path: str
    """
    The path that is accessible to staff from their computers
    """
    segel_brief: str | None = None


class Notification(HiveCoreItem):
    id: int
    help: int | None = None
    assignment: int | None = None
    response_type: NotificationResponseTypeEnum
    exercise_id: Annotated[int | None, Field(alias="exercise")]
    exercise_name: Annotated[str | None, Field(...)]
    module_id: Annotated[int | None, Field(alias="module")]
    subject: Annotated[int | None, Field(...)]
    program_id: Annotated[int | None, Field(alias="program")]
    help_type: Annotated[HelpTypeEnum | None, Field(...)]
    help_title: Annotated[str | None, Field(...)]
    comment: str | None = None
    from_user_id: Annotated[int | None, Field(alias="from_user")]
    from_user_name: str
    was_read: bool | None = None
    time: datetime
    for_user: int
    for_user_name: str


class PaginatedHelpList(HiveCoreItem):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[
        str | None,
        Field(examples=["http://api.example.org/accounts/?offset=400&limit=100"]),
    ] = None
    previous: Annotated[
        str | None,
        Field(examples=["http://api.example.org/accounts/?offset=200&limit=100"]),
    ] = None
    results: list[Help]


class Program(HiveCoreItem):
    id: int
    name: str
    checker_id: Annotated[int, Field(alias="checker")]
    default_class_id: Annotated[int | None, Field(alias="default_class")] = None
    auto_toilet: bool | None = None
    hanich_raise_hand: bool | None = None
    auto_schedule: bool | None = None
    auto_room: bool | None = None
    hanich_day_only: bool | None = None
    auto_toilet_count: int | None = None
    hanich_classes_only: bool | None = None
    hanich_schedule: bool | None = None
    sync_status: SyncStatusEnum
    sync_message: str | None = None


class QueueItem(HiveCoreItem):
    id: int
    order: int
    exercise_id: Annotated[Exercise | None, Field(alias="exercise")]
    nested_queue: Annotated[Queue | None, Field(...)]
    queue_rule: QueueRuleEnum
    continue_on_redo: bool | None = None
    enabled: bool


class Subject(HiveCoreItem):
    id: int
    symbol: str
    parent_program_id: Annotated[int, Field(alias="parent_program")]
    color: str
    name: str
    parent_program_name: str
    sync_status: SyncStatusEnum
    sync_message: str | None = None
    segel_path: str
    """
    The path that is accessible to staff from their computers
    """
    segel_brief: str | None = None
